// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Human struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewHuman struct {
	Name string `json:"name"`
}
